### ISSUE TITLE
Automatically approve PRs from safelisted contributors

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-pr-bot#47]
In the joint web-platform-tests + CSSWG meeting at TPAC today, the problem of PR review in CSS was raised, in particular when CSSWG editors have written tests it can be hard to find reviewers, and review is much more difficult than it seems at face value, because you need deep knowledge of the spec to understand it.

To alleviate this, we suggested to automatically approve PRs from certain accounts, at least @fantasai @frivoal and @tabatkins.

Minutes: https://www.w3.org/2018/10/22-css-minutes.html#item20

**Comment by tabatkins** [comment]
To restate the argument slightly more strongly: often the best people to review a test is the spec editor; they have the deep knowledge of the spec to know if the test is correct. When some outside person writes the test, the editor can review, and everything's fine; when the editor writes the test, they have to find an outside person willing to put in the sometimes-very-large amount of effort to properly grok the spec and do a good review.

So, since the editor is already the best reviewer, simply by virtue of being the writer, they've already achieved a large portion of the quality control that our review requirement is meant to provide.

Further, when writing tests for new features or changes, the implementor who sees they're freshly failing a test is likely to review the test anyway, so we will have additional review anyway, post-merging. We don't *usually* want to rely on this for random tests — it's bad to have implementors spending time rejecting low-quality tests — but since this scenario *should* already guarantee at least decent-quality tests, it won't be too bad.

**Comment by gsnedders** [comment]
Presumably this should be a new section in the META.yml files.

**Comment by tabatkins** [comment]
Is it possible to distinguish this per-directory?

**Comment by foolip** [comment]
Yeah, we could add a `automatically_approve_prs_for_these_authors` field to META.yml on a per-directory basis.

**Comment by jugglinmike** [comment]
Thanks for taking and sharing the meeting minutes! Those notes jump abruptly
from a discussion of the problem (insufficient bandwidth for peer review) to a
technical solution (disable the peer review requirement). I was not present,
and I'm not a member of the CSS WG, so I may be missing some context. I'm
obliged to push back, if only to make sure that context is recorded somewhere.

Florian noted:

> Reviewing one test might be a 20-hour task, as you have to read the spec
> first.

This explains why it can be hard to get review, but it also highlights what
makes review so important. My professional experience writing tests on behalf
of editors and spec authors makes me very wary to forgo the process.

It calls to mind a comment that Fremy made while discussing the challenge of
writing tests in the first place:

> We have big companies here, we should make sure we staff the testing group
> specifically.

Can't the same be said for peer review?

**Comment by tabatkins** [comment]
My comment above captured some of the missing context from the meeting. In particular:

> So, since the editor is already the best reviewer, simply by virtue of being the writer, they've already achieved a large portion of the quality control that our review requirement is meant to provide.

This definitely isn't *perfect*, but it at least captures a good fraction of the purpose of review, while avoiding the reversal of expected review-effort that "make the editors contribute tests" otherwise suffers from.

**Comment by zcorpan** [comment]
I think we should try this and evaluate how well it works after 6 months. The current situation is basically worse I believe, because these PRs aren't getting reviewed and don't reach implementers. Implementers would review the tests when they look at them because they are failing.

**Comment by gsnedders** [comment]
I share many of @jugglinmike's concerns here, though I didn't bother voicing them in the meeting.

The argument we can just rely on implementers reviewing tests when they look at failing tests is only really half the battle (it provides no review of tests that turn out to be tautological), and is surely true for *all* of WPT.

I'd much rather we try and figure out *why* getting review of CSS tests is so much harder than most of the rest of WPT; it's definitely not the case that review requests on the Gecko or Blink repositories tend to go unreviewed for many months, even for layout code and tests, which implies it's not the difficulty of review, but rather getting people involved in the WPT upstream repo.

One thing I discussed with someone at TPAC was the possibility of adding a delay to whitelisted people from being able to merge without review, except that would further reduce the motivation for reviewers to engage (especially with those PRs!), so it's probably not worth it.

At the very least, I think that if we reach a point where *other* layout PRs are getting timely review we should very seriously consider dropping this.

**Comment by zcorpan** [comment]
We could also do https://github.com/web-platform-tests/wpt/issues/13686 and https://github.com/web-platform-tests/wpt/issues/13722 first and see if this is still a problem.

**Comment by foolip** [comment]
> it provides no review of tests that turn out to be tautological

Having results+regressions reported clearly on PRs, including screenshots, will make this much less of a problem I think. If the test is unexpectedly passing everywhere, that'll be pretty hard to overlook. And if it is overlooked, it's still pretty harmless, it just means the that specific test isn't doing anything usful.

> I'd much rather we try and figure out *why* getting review of CSS tests is so much harder than most of the rest of WPT

If we run the numbers on review response time I'm not sure that it is. It's just that we treat css/ as one thing in these discussions, and other things don't group together and look like a problem.

I think we should do https://github.com/web-platform-tests/wpt/issues/13686 and @jugglinmike is going to estimate how much work that is.

But I still think we should do this, because it'll solve a real and immediate problem. If not, I volunteer to rubberstamp PRs with very light review, or @tabatkins and @fantasai could rubberstamp each other's PRs, but that's only a cosmetic improvement, the amount valuable review is only increased by a tiny fraction.

**Comment by frivoal** [comment]
As much as I agree that editors are not immune to making mistakes, might write tests for things that they intended to write in the spec instead of what they actually wrote, and various other reasons for reviews on editors written tests being a valuable thing, I think that some tests are better than no tests, so I support this.

As an editor who writes tests, I will continue to seek review of them, but if they take too long to land, being able to just merge them seems useful.

**Comment by foolip** [comment]
This was resolved by https://github.com/web-platform-tests/wpt-pr-bot/pull/52.

@fantasai @frivoal @tabatkins has it been working for you?

**Comment by frivoal** [comment]
Wasn't aware it had happened, and recently had been busy with other things. I'll try it out, and will report back if anything doesn't work.
